show_author_username:
  type: bool
  default: false
  description:
    en: "Show author usernames instead profile avatars in all topic list pages."

show_topic_author_column_first:
  type: bool
  default: false
  description:
    en: "Show topic authors in the first column in all topic list pages."

show_topic_author_column_last:
  type: bool
  default: false
  description:
    en: "Show topic authors in the last column in all topic list pages. Above setting must be disabled. Leaving both disabled shows default column order."

show_topic_author_column_last_on_categories_page:
  type: bool
  default: false
  description:
    en: "Show topic authors in the last column on the desktop view category homepage. Leave disabled for default first column."
